name: Native Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos
            os: macos-latest
            graal: 22.3.1
          - nickname: linux
            os: ubuntu-latest
            graal: 22.3.1
          - nickname: windows
            os: windows-latest
            graal: 22.3.1
    name: Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 17
          components: native-image
          set-java-home: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ./gradlew clean build nativeBuild
