name: Native Build3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos-jdk17
            os: macos-latest
            java: 17
          - nickname: linux-jdk17
            os: ubuntu-latest
            java: 17
          - nickname: windows-jdk17
            os: windows-latest
            java: 17
          - nickname: windows-jdk21
            os: windows-latest
            java: 21
          - nickname: windows-dev
            os: windows-latest
            java: dev
    name: Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: ${{ matrix.java }}
          components: native-image
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ./gradlew clean build nativeBuild
